import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useState, useEffect } from "react";

import useSWR from "swr";

import initializeMap from "./initializeMap";
import addDataLayer from "./addDataLayer";
import { NextPage } from "next";

const mapboxgl = require("mapbox-gl/dist/mapbox-gl.js");

mapboxgl.accessToken =
  "pk.eyJ1IjoibW9uZzAweCIsImEiOiJjbDFuZWNwbTAwMTl4M2txcDExMnZpeGdxIn0.b7ny8BC4Df1STWo_TB1o9w";

  
  async function fetcher(params: RequestInfo) {
    try {
      const response = await fetch(params);
      const responseJSON = await response.json();
      return responseJSON;
    } catch (error) {
      console.error("Fetcher error: " + error);
      return {};
    }
  }

const Home: NextPage = () => {
  const [pageIsMounted, setPageIsMounted] = useState(false);
  const [Map, setMap] = useState();

  const { data, error } = useSWR("/api/liveMusic", fetcher);

  useEffect(() => {
    setPageIsMounted(true);

    const map = new mapboxgl.Map({
      container: "mapContainer",
      style: "mapbox://styles/mapbox/streets-v11",
      center: [133.202036, -25.198914],
      zoom: 2.9,
      pitch: 10,
    });

    initializeMap(mapboxgl, map);
    setMap(map);
  }, []);

  useEffect(() => {
    if (pageIsMounted && data) {
      Map.on("load", function () {
        addDataLayer(Map, data);
      });
    }
  }, [pageIsMounted, setMap, data, Map]);
  return (
   

      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div id="mapContainer" style={{ height: 500, width: 500 }} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="/vercel.svg"
              alt="
            Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;



