import type { NextPage } from "next";
import Head from "next/head";

import React, { useState } from "react";

import Map from "react-map-gl";
import { Button,Offcanvas } from "react-bootstrap";
import CreateEventModal from "../../components/createEventModal";
import Profile from "../../components/Profile";
const Home: NextPage = () => {
  const [showCreateEventModal, setShowCreateEventModal] =
    useState<boolean>(false);

  const [showProfile, setShowProfile] = useState<boolean>(false);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css"
          rel="stylesheet"
        />
      </Head>

      <main
        style={{
          minHeight: "100vh",
          flex: "1",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <h1
          style={{
            zIndex: "2",
            background: "white",
            padding: "5px",
            opacity: "0.8",
            borderRadius: "15px",
          }}
        >
          Welcome to <a href="#">Australia!</a>
        </h1>

        <Button
          style={{
            zIndex: "2",
            background: "white",
            borderColor: "white",
            color: "blue",
            position: "fixed",
            top: "0",
            right: "0",
            marginTop: "25px",
            marginRight: "30px",
            fontWeight: "500",
          }}
          onClick={() => {
            setShowCreateEventModal(true);
          }}
        >
          Create Event
        </Button>

        <CreateEventModal
          showModal={showCreateEventModal}
          setShowModal={setShowCreateEventModal}
        />
      
        <Button variant="primary" 
        style={{
          zIndex: "2",
          background: "white",
          borderColor: "white",
          color: "blue",
          position: "fixed",
          top: "0",
          left: "0",
          marginTop: "25px",
          marginLeft: "25px",
          fontWeight: "500",
        }}
        onClick={()=> {setShowProfile(!showProfile)}}>
        Profile
        </Button>
        <Offcanvas show={showProfile} onHide={()=>setShowProfile(false)}>
        <Offcanvas.Header closeButton>
          <Offcanvas.Title>Offcanvas</Offcanvas.Title>
        </Offcanvas.Header>
        <Offcanvas.Body>
        <Profile />
        </Offcanvas.Body>
      </Offcanvas>
       

        <Map
          initialViewState={{
            latitude: -37.85,
            longitude: 145,
            zoom: 12,
          }}
          style={{
            width: "100vw",
            height: "100vh",
            position: "absolute",
            zIndex: 1,
          }}
          mapStyle="mapbox://styles/mong00x/cl1qkztx0000m15o5638w9apn"
          mapboxAccessToken={process.env.MAPBOX_TOKEN}
        />
      </main>
    </div>
  );
};

export default Home;
