import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

import * as React from 'react';

import Map from 'react-map-gl';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css"
            rel="stylesheet"
          />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{zIndex: 2}}>
          Welcome to <a href="#">Atustralia!</a>
        </h1>
<div>
  
</div>
        <Map
        initialViewState={{
          latitude: -30,
          longitude: 135,
          zoom: 3
        }}
        style={{width: '100vw', height: '100vh', position: 'absolute', zIndex: 1}}
        mapStyle="mapbox://styles/mong00x/cl1qkztx0000m15o5638w9apn"
        mapboxAccessToken={process.env.MAPBOX_TOKEN}
      
        />

      </main>


    </div>
  );
};

export default Home;
